cmake ../ -G"Unix Makefiles" -DPROJ_CONFIG="C:/NewTFM1/trusted-firmware-m/ConfigPsaApiTest.cmake" -DTARGET_PLATFORM=M2351 -DCOMPILER=ARMCLANG -DCMAKE_BUILD_TYPE=Debug -DMBEDTLS_DEBUG=ON -DPSA_API_TEST_SECURE_STORAGE=ON

